app = "narou-search-backend"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  ENV = "production"

[mounts]
  source = "narou_data"
  destination = "/app/db"
